name: nice-dns

x-health-defaults: &probe          # central place for timings
  interval: 30s
  timeout: 5s
  retries: 3
  start_period: 10s

networks:
  dnsnet:
    external: true

services:

  tor-socat:
    container_name: tor-socat
    image: sureserver/tor-socat:latest
    environment:
      - BRIDGE1=${BRIDGENV1}
      - BRIDGE2=${BRIDGENV2}
      - BRIDGED=${BRIDGEDVAR}
    networks:
      dnsnet:
        ipv4_address: 172.31.240.252
    healthcheck:
      test: ["CMD", "dig +short +tls +norecurse +retry=0 -p 853 @127.0.0.1 google.com || exit 1"]
      <<: *probe

  unbound:
    container_name: unbound
    build: unbound/
    networks:
      dnsnet:
        ipv4_address: 172.31.240.251
    healthcheck:
      test: ["CMD", "dig +short +norecurse +retry=0 -p 5335 @127.0.0.1 google.com || exit 1"]
      <<: *probe

  pi-hole:
    container_name: pi-hole
    build: pihole/
    ports:
      - 2053:53/tcp
      - 2053:53/udp
      - ${WEBPORT}:80      
    networks:
      dnsnet:
        ipv4_address: 172.31.240.250
    environment:
    - TZ=Europe/London
    - DNS1=172.31.240.251
    - DISABLE_GITHUB_UPDATES=true
    healthcheck:
      <<: *probe



