name: nice-dns

networks:
  dnsnet:
    ipam:
      config:
        - subnet: 192.168.180.240/29


services:

  tor-socat:
    container_name: tor-socat
    restart: always
    image: 	sureserver/tor-socat:latest
    networks:
      dnsnet:
        ipv4_address: 192.168.180.244

  unbound:
    container_name: unbound
    restart: unless-stopped
    build: unbound/
    networks:
      dnsnet:
        ipv4_address: 192.168.180.243

  pi-hole:
    container_name: pi-hole
    restart: unless-stopped
    build: pihole/
    ports:
      - 53:53/tcp
      - 53:53/udp     
    networks:
      dnsnet:
        ipv4_address: 192.168.180.242


