name: nice-dns

networks:
  dnsnet:
    ipam:
      config:
        - subnet: 172.31.240.248/29


services:

  tor-socat:
    container_name: tor-socat
    restart: always
    image: sureserver/tor-socat:latest
    environment:
      - BRIDGE1=${BRIDGENV1}
      - BRIDGE2=${BRIDGENV2}
      - BRIDGED=${BRIDGEDVAR}
    networks:
      dnsnet:
        ipv4_address: 172.31.240.252

  unbound:
    container_name: unbound
    restart: unless-stopped
    build: unbound/
    networks:
      dnsnet:
        ipv4_address: 172.31.240.251

  pi-hole:
    container_name: pi-hole
    restart: unless-stopped
    build: pihole/
    ports:
      - 2053:53/tcp
      - 2053:53/udp
      - ${WEBPORT}:80      
    networks:
      dnsnet:
        ipv4_address: 172.31.240.250


