# shellcheck shell=bash
# Group integration/dns-transaction (Sub-plan 4, Task 1.2; ARCH-03, ARCH-06;
# WF-DNS-003).
#
# Sourced by tests/run.sh (assert_* helpers; NICE_DNS_ROOT, CASE_DIR). The
# DNS helpers (deb/custom-dns-deb, mac/start-container-root.sh) and the four
# public entrypoints run in a world: a private HOME, a copy of the checkout,
# PATH stubs, and a fake root ($FAKE_ROOT) that holds /etc/resolv.conf,
# systemd unit state, sysctl values and the macOS network services
# (tests/fixtures/install-fakes.sh). The helpers honour that root through
# ND_DNS_TEST_ROOT only when not run as root. Nothing on the host is touched.
#
# NICE_DNS_OPT_PLATFORMS (--platforms all|linux|macos) picks the helper
# platforms; NICE_DNS_OPT_ENTRYPOINTS (--entrypoints ...) the entrypoints.

. "$NICE_DNS_ROOT/tests/fixtures/install-fakes.sh"

DT_PIN_MAC=172.31.240.250

dt_platforms() {
  local p="${NICE_DNS_OPT_PLATFORMS:-all}" x out=""
  [ "$p" = all ] && { printf 'linux macos\n'; return 0; }
  for x in $(printf '%s' "$p" | tr ',' ' '); do
    case "$x" in linux|macos) out="$out $x" ;; *) fail "unknown --platforms value '$x' (all, linux, macos)" ;; esac
  done
  printf '%s\n' "$out"
}
dt_select_platforms() { DT_PLATS="$(dt_platforms)" || exit 1; }
dt_ep_of() { if [ "$1" = linux ]; then echo install-deb; else echo install-mac; fi; }

# dt_world <entrypoint> <state>: ip_env plus a fake root in <state>.
#   linux: resolved (resolv.conf -> the systemd-resolved stub), file (a plain
#          DHCP resolv.conf), missing, legacy (an install from before records)
#   macos: fresh (Wi-Fi 192.168.1.1, Ethernet 9.9.9.9 149.112.112.112,
#          Thunderbolt Bridge empty), legacy (every service pinned)
dt_world() {
  local ep="$1" st="$2" r
  ip_env "$ep"
  FAKE_ROOT="$IP_W/root"; r="$FAKE_ROOT"
  mkdir -p "$r/etc" "$r/.systemd" "$r/.sysctl" "$r/run/systemd/resolve" "$r/usr/bin" "$r/usr/local/sbin"
  if [ "$(ip_platform "$ep")" = linux ]; then
    printf 'nameserver 127.0.0.53\noptions edns0 trust-ad\n' >"$r/run/systemd/resolve/stub-resolv.conf"
    : >"$r/.systemd/systemd-resolved.unit"; : >"$r/.systemd/NetworkManager.unit"
    echo enabled >"$r/.systemd/systemd-resolved.enabled"; echo active >"$r/.systemd/systemd-resolved.active"
    echo enabled >"$r/.systemd/NetworkManager.enabled"; echo active >"$r/.systemd/NetworkManager.active"
    printf '0\n' >"$r/.sysctl/net.ipv6.conf.all.disable_ipv6"
    printf '0\n' >"$r/.sysctl/net.ipv6.conf.default.disable_ipv6"
    printf '0\n' >"$r/.sysctl/net.ipv6.conf.lo.disable_ipv6"
    case "$st" in
      resolved) ln -s ../run/systemd/resolve/stub-resolv.conf "$r/etc/resolv.conf" ;;
      file) printf '# Generated by NetworkManager\nsearch lan\nnameserver 192.168.1.1\n' >"$r/etc/resolv.conf"; chmod 644 "$r/etc/resolv.conf" ;;
      missing) ;;
      legacy)
        printf 'nameserver 127.0.0.1\n' >"$r/etc/resolv.conf"
        echo disabled >"$r/.systemd/systemd-resolved.enabled"; echo inactive >"$r/.systemd/systemd-resolved.active"
        mkdir -p "$r/etc/NetworkManager/conf.d" "$r/etc/systemd/system"
        printf '[main]\ndns=none\n' >"$r/etc/NetworkManager/conf.d/90-nice-dns.conf"
        : >"$r/etc/systemd/system/custom-dns-deb.service" ;;
    esac
  else
    mkdir -p "$r/.netsvc/dns"
    printf '%s\n' "$IP_TREE/mac/start-container-root.sh" >"$FAKE/agent_helper"
    printf 'Wi-Fi\nEthernet\nThunderbolt Bridge\n' >"$r/.netsvc/list"
    case "$st" in
      fresh)
        printf '192.168.1.1\n' >"$r/.netsvc/dns/Wi-Fi"
        printf '9.9.9.9\n149.112.112.112\n' >"$r/.netsvc/dns/Ethernet" ;;
      legacy)
        for s in Wi-Fi Ethernet 'Thunderbolt Bridge'; do printf '%s\n' "$DT_PIN_MAC" >"$r/.netsvc/dns/$s"; done
        : >"$r/usr/local/sbin/start-container.sh" ;;
    esac
  fi
  export FAKE_ROOT
}

# dt_dns_state: the host DNS state the installers own, canonical, for exact
# comparison (the helpers' own record is not part of it).
dt_dns_state() {
  local r="$FAKE_ROOT" f k s
  if [ -f "$r/.netsvc/list" ]; then
    while IFS= read -r s; do printf 'service %s: %s\n' "$s" "$(cat "$r/.netsvc/dns/$s" 2>/dev/null | tr '\n' ' ' | sed 's/ $//')"; done <"$r/.netsvc/list"
    return 0
  fi
  if [ -L "$r/etc/resolv.conf" ]; then printf 'resolv symlink %s\n' "$(readlink "$r/etc/resolv.conf")"
  elif [ -f "$r/etc/resolv.conf" ]; then printf 'resolv file %s\n' "$(ip_mode "$r/etc/resolv.conf")"; sed 's/^/  /' "$r/etc/resolv.conf"
  else echo 'resolv missing'; fi
  for k in systemd-resolved.enabled systemd-resolved.active; do printf '%s %s\n' "$k" "$(cat "$r/.systemd/$k" 2>/dev/null)"; done
  for k in all default lo; do printf 'sysctl %s %s\n' "$k" "$(cat "$r/.sysctl/net.ipv6.conf.$k.disable_ipv6" 2>/dev/null)"; done
  for f in etc/NetworkManager/conf.d/90-nice-dns.conf etc/NetworkManager/dispatcher.d/90-nice-dns-pin \
           etc/systemd/system/custom-dns-deb.service etc/sysctl.d/99-nice-dns-disable-ipv6.conf \
           etc/systemd/system/NetworkManager-wait-online.service.d/10-wait-for-connectivity.conf usr/bin/custom-dns-deb; do
    [ -e "$r/$f" ] && printf 'owned %s\n' "$f"
  done
  return 0
}

# dt_pinned: every owned resolver setting points at the stack.
dt_pinned() {
  local s
  if [ -f "$FAKE_ROOT/.netsvc/list" ]; then
    while IFS= read -r s; do [ "$(cat "$FAKE_ROOT/.netsvc/dns/$s" 2>/dev/null)" = "$DT_PIN_MAC" ] || return 1; done <"$FAKE_ROOT/.netsvc/list"
    return 0
  fi
  [ -f "$FAKE_ROOT/etc/resolv.conf" ] && [ ! -L "$FAKE_ROOT/etc/resolv.conf" ] && [ "$(cat "$FAKE_ROOT/etc/resolv.conf")" = 'nameserver 127.0.0.1' ]
}

# dt_helper <platform> <verb>: one helper call as the installer makes it.
dt_helper() {
  local h
  if [ "$1" = linux ]; then h="$IP_TREE/deb/custom-dns-deb"; else h="$IP_TREE/mac/start-container-root.sh"; fi
  DT_OUT="$(env -i HOME="$IP_HOME" PATH="$IP_BIN" FAKE="$FAKE" FAKE_LOG="$FAKE_LOG" FAKE_ROOT="$FAKE_ROOT" \
    ND_DNS_TEST_ROOT="$FAKE_ROOT" bash "$h" "$2" 2>&1)"
  DT_RC=$?
}
dt_pin_verb() { if [ "$1" = linux ]; then echo pin; else echo post; fi; }
dt_receipt() { if [ "$1" = linux ]; then echo "$FAKE_ROOT/var/lib/nice-dns/dns-owned/receipt.tsv"; else echo "$FAKE_ROOT/var/db/nice-dns/dns-owned/receipt.tsv"; fi; }

# dt_deploy_state: the deployment an install replaces (marker files, the
# :latest images the stack runs, whether it answers).
dt_deploy_state() {
  local f
  for f in "$IP_HOME/.config/containers/systemd"/* "$IP_HOME/.local/bin/nice-dns-health" \
           "$IP_HOME/Library/LaunchAgents"/*.plist "$FAKE_ROOT/usr/local/sbin"/* "$FAKE_ROOT/etc/sudoers.d"/*; do
    [ -f "$f" ] && printf '%s: %s\n' "${f#"$IP_W"/}" "$(cat "$f")"
  done
  # The references the stack runs; pulled upstream bases are build inputs.
  awk '$1 ~ /^(localhost\/)?(unbound|pi-hole|pi-hole-hardened-base):latest$|^docker\.io\/sureserver\/tor-(haproxy|socat):latest$/' \
    "$FAKE/images" 2>/dev/null | sort
  [ -f "$FAKE/dns_up" ] && echo 'stack answers'
  return 0
}

# dt_installed <entrypoint>: a completed install at source A, log cleared,
# the next install at source B.
dt_installed() {
  ip_install "$1"
  assert_rc 0 "$IP_RC" "$1: the first install: $IP_OUT"
  : >"$FAKE_LOG"
  printf 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n' >"$FAKE/git_head"
}

dt_linux_states() { printf 'resolved file missing\n'; }
dt_fresh_state() { if [ "$(ip_platform "$1")" = linux ]; then echo resolved; else echo fresh; fi; }

# ─────────────────────────── helper cases ───────────────────────────────

t_helper_snapshot_and_restore_are_exact() {
  local plat st sts
  dt_select_platforms
  for plat in $DT_PLATS; do
    if [ "$plat" = linux ]; then sts="$(dt_linux_states)"; else sts=fresh; fi
    for st in $sts; do
      (
        local before rec
        dt_world "$(dt_ep_of "$plat")" "$st"
        before="$(dt_dns_state)"
        dt_helper "$plat" snapshot
        assert_rc 0 "$DT_RC" "$plat/$st: snapshot: $DT_OUT"
        rec="$(dt_receipt "$plat")"
        assert_file "$rec" "$plat/$st: the record"
        assert_eq 600 "$(ip_mode "$rec")" "$plat/$st: the record is 0600"
        assert_eq 700 "$(ip_mode "$(dirname "$rec")")" "$plat/$st: its directory is 0700"
        assert_eq "$(printf 'schema\tnice-dns-dns-owned/1')" "$(head -n 1 "$rec")" "$plat/$st: schema"
        assert_eq fresh "$(awk -F '\t' '$1 == "origin" { print $2 }' "$rec")" "$plat/$st: origin"
        dt_helper "$plat" "$(dt_pin_verb "$plat")"
        assert_rc 0 "$DT_RC" "$plat/$st: pin: $DT_OUT"
        dt_pinned || fail "$plat/$st: pinned after the pin: $(dt_dns_state)"
        dt_helper "$plat" snapshot
        assert_eq fresh "$(awk -F '\t' '$1 == "origin" { print $2 }' "$rec")" "$plat/$st: a second snapshot keeps the first record"
        dt_helper "$plat" check
        assert_rc 0 "$DT_RC" "$plat/$st: the pinned state passes the check: $DT_OUT"
        dt_helper "$plat" restore
        assert_rc 0 "$DT_RC" "$plat/$st: restore: $DT_OUT"
        assert_eq "$before" "$(dt_dns_state)" "$plat/$st: restore gives back exactly the recorded state"
        assert_no_path "$rec" "$plat/$st: the record is gone after restore"
      ) || exit 1
    done
  done
}

t_helper_refuses_external_changes() {
  local plat
  dt_select_platforms
  for plat in $DT_PLATS; do
    (
      dt_world "$(dt_ep_of "$plat")" "$( [ "$plat" = linux ] && echo file || echo fresh)"
      dt_helper "$plat" snapshot; dt_helper "$plat" "$(dt_pin_verb "$plat")"
      if [ "$plat" = linux ]; then
        rm -f "$FAKE_ROOT/etc/resolv.conf"; printf 'nameserver 10.64.0.1\n' >"$FAKE_ROOT/etc/resolv.conf"
      else
        printf '10.64.0.1\n' >"$FAKE_ROOT/.netsvc/dns/Wi-Fi"
      fi
      dt_helper "$plat" check
      assert_rc 3 "$DT_RC" "$plat: another owner's change is refused: $DT_OUT"
      assert_match 'another owner' "$DT_OUT" "$plat: and named"
      dt_helper "$plat" restore
      assert_rc 0 "$DT_RC" "$plat: restore: $DT_OUT"
      if [ "$plat" = linux ]; then
        assert_eq 'nameserver 10.64.0.1' "$(cat "$FAKE_ROOT/etc/resolv.conf")" "$plat: restore leaves another owner's resolv.conf"
      else
        assert_eq 10.64.0.1 "$(cat "$FAKE_ROOT/.netsvc/dns/Wi-Fi")" "$plat: restore leaves another owner's service"
        assert_eq '9.9.9.9 149.112.112.112' "$(tr '\n' ' ' <"$FAKE_ROOT/.netsvc/dns/Ethernet" | sed 's/ $//')" "$plat: and restores the others"
      fi
    ) || exit 1
  done
}

t_legacy_install_is_recorded_as_legacy() {
  local plat
  dt_select_platforms
  for plat in $DT_PLATS; do
    (
      dt_world "$(dt_ep_of "$plat")" legacy
      dt_helper "$plat" snapshot
      assert_eq legacy "$(awk -F '\t' '$1 == "origin" { print $2 }' "$(dt_receipt "$plat")")" "$plat: an install from before records is legacy"
      dt_helper "$plat" restore
      assert_rc 0 "$DT_RC" "$plat: restore: $DT_OUT"
      if [ "$plat" = linux ]; then
        # The state before nice-dns is unknown: the distribution default.
        assert_eq ../run/systemd/resolve/stub-resolv.conf "$(readlink "$FAKE_ROOT/etc/resolv.conf")" "$plat: resolv.conf is the systemd-resolved stub again"
        assert_eq enabled "$(cat "$FAKE_ROOT/.systemd/systemd-resolved.enabled")" "$plat: systemd-resolved enabled"
        assert_eq active "$(cat "$FAKE_ROOT/.systemd/systemd-resolved.active")" "$plat: and running"
        assert_no_path "$FAKE_ROOT/etc/NetworkManager/conf.d/90-nice-dns.conf" "$plat: the NetworkManager override goes"
      else
        assert_eq "$(printf 'service Wi-Fi: \nservice Ethernet: \nservice Thunderbolt Bridge: ')" "$(dt_dns_state)" "$plat: every pinned service goes back to Empty (DHCP)"
      fi
    ) || exit 1
  done
}

# ─────────────────────────── entrypoint cases ───────────────────────────

t_fresh_install_pins_after_controller_and_readiness() {
  local ep
  ip_select
  for ep in $IP_EPS; do
    (
      local snap pers ready pin start chk
      dt_world "$ep" "$(dt_fresh_state "$ep")"
      ip_install "$ep"
      assert_rc 0 "$IP_RC" "$ep: $IP_OUT"
      dt_pinned || fail "$ep: the host resolver is pinned at the end: $(dt_dns_state)"
      snap="$(ip_first "$FAKE_LOG" '(custom-dns-deb|start-container-root\.sh) snapshot$')"
      pers="$(ip_last "$FAKE_LOG" '^(persistent-podman|persist)\.sh ')"
      pin="$(ip_first "$FAKE_LOG" '^sudo ([^ ]*/)?(usr/bin/custom-dns-deb|bash [^ ]*/custom-dns-deb) pin$|^sudo bash [^ ]*/start-container-root\.sh post$|^agent: start-container-root\.sh post$')"
      assert_ne "" "$snap" "$ep: the owned state is recorded"
      assert_ne "" "$pin" "$ep: the resolver is pinned"
      # The chain answers after the new stack started (Linux: the pod
      # restart in persistent-podman.sh; macOS: the proxy container) and
      # before the pin.
      start="$(ip_last "$FAKE_LOG" '^(persistent-podman\.sh |container run -d --name tor-)')"
      ready="$(ip_lines "$FAKE_LOG" '^dig @(127\.0\.0\.1|172\.31\.240\.250) ' | awk -F: -v a="$start" -v b="$pin" '$1 > a && $1 < b' | head -n 1)"
      assert_eq 1 "$((snap < $(ip_first "$FAKE_LOG" "$IP_DISRUPTIVE")))" "$ep: the record precedes every disruptive call:
$(cat -n "$FAKE_LOG")"
      chk="$(ip_first "$FAKE_LOG" '^nice-dns-health self-check$')"
      assert_ne "" "$chk" "$ep: the installed controller's self-check ran"
      assert_eq 1 "$((chk < pin))" "$ep: the installed controller passed its self-check (line $chk) before the first pin (line $pin), the agent's included:
$(cat -n "$FAKE_LOG")"
      assert_eq 1 "$((pers < pin))" "$ep: the controller is installed (line $pers) before the pin (line $pin):
$(cat -n "$FAKE_LOG")"
      assert_ne "" "$ready" "$ep: the chain answers after the stack starts (line $start) and before the pin:
$(cat -n "$FAKE_LOG")"
      assert_file "$IP_STATE/current" "$ep: the generation is current"
    ) || exit 1
  done
}

# dt_rollback_case <entrypoint> <fresh|reinstall> <injection>: an install
# that fails after the interruption leaves DNS and the deployment as they were.
dt_rollback_case() {
  local ep="$1" mode="$2" inj="$3" dns0 dep0 cur0
  dt_world "$ep" "$(dt_fresh_state "$ep")"
  [ "$mode" = reinstall ] && dt_installed "$ep"
  dns0="$(dt_dns_state)"; dep0="$(dt_deploy_state)"; cur0="$(cat "$IP_STATE/current" 2>/dev/null)"
  case "$inj" in
    persist_fail|never_ready|selfcheck_fail|probe_fail) : >"$FAKE/$inj" ;;
    sigint:*) printf '%s\n' "${inj#sigint:}" >"$FAKE/sigint" ;;
    *) printf '%s\n' "$inj" >"$FAKE/fail" ;;
  esac
  ip_install "$ep" socat
  assert_nonzero "$IP_RC" "$ep/$mode/$inj: the install fails: $IP_OUT"
  rm -f "$FAKE/fail" "$FAKE/sigint" "$FAKE/persist_fail" "$FAKE/never_ready" "$FAKE/selfcheck_fail" "$FAKE/probe_fail"
  assert_eq "$dns0" "$(dt_dns_state)" "$ep/$mode/$inj: host DNS is exactly as before:
$(cat -n "$FAKE_LOG")"
  assert_eq "$dep0" "$(dt_deploy_state)" "$ep/$mode/$inj: the prior deployment is back:
$(cat -n "$FAKE_LOG")"
  assert_eq "$cur0" "$(cat "$IP_STATE/current" 2>/dev/null)" "$ep/$mode/$inj: the current generation is unchanged"
  if [ "$mode" = fresh ]; then
    assert_eq "" "$(ip_lines "$FAKE_LOG" '^sudo ([^ ]*/)?(usr/bin/custom-dns-deb|bash [^ ]*/custom-dns-deb) pin$|^sudo bash [^ ]*/start-container-root\.sh post$|^agent: start-container-root\.sh post$')" "$ep/$mode/$inj: nothing was pinned"
    assert_no_path "$(dt_receipt "$(ip_platform "$ep")")" "$ep/$mode/$inj: the unused record is discarded"
  fi
  assert_match 'rolled back|rolling back|Rolling back' "$IP_OUT" "$ep/$mode/$inj: the rollback is reported"
  assert_not_match 'another owner' "$IP_OUT" "$ep/$mode/$inj: no false ownership warning"
}

dt_injections() {
  if [ "$(ip_platform "$1")" = linux ]; then
    printf '%s\n' persist_fail never_ready selfcheck_fail probe_fail '^podman system migrate' '^podman tag localhost/unbound:[0-9]' \
      'sigint:^podman system migrate' 'sigint:^podman pod rm -f nice-dns$'
  else
    printf '%s\n' persist_fail never_ready selfcheck_fail probe_fail '^container build ' '^container network create ' \
      'sigint:^container build ' 'sigint:^container stop pi-hole$'
  fi
}

t_failed_controller_install_leaves_dns_as_it_was() {
  local ep mode
  ip_select
  for ep in $IP_EPS; do
    for mode in fresh reinstall; do
      ( dt_rollback_case "$ep" "$mode" persist_fail ) || exit 1
    done
  done
}

t_failed_activation_rolls_back_the_deployment() {
  local ep inj
  ip_select
  for ep in $IP_EPS; do
    while IFS= read -r inj; do
      [ "$inj" = persist_fail ] && continue
      ( dt_rollback_case "$ep" reinstall "$inj" ) || exit 1
      ( dt_rollback_case "$ep" fresh "$inj" ) || exit 1
    done <<EOF
$(dt_injections "$ep")
EOF
  done
}

t_reinstall_holds_the_controller() {
  local ep
  ip_select
  for ep in $IP_EPS; do
    (
      local hold first
      dt_world "$ep" "$(dt_fresh_state "$ep")"
      dt_installed "$ep"
      : >"$FAKE/never_ready"
      ip_install "$ep"
      assert_nonzero "$IP_RC" "$ep: $IP_OUT"
      if [ "$(ip_platform "$ep")" = linux ]; then
        hold="$(ip_first "$FAKE_LOG" '^systemctl --user stop nice-dns-health\.timer')"
        first="$(ip_first "$FAKE_LOG" '^podman pod rm')"
        assert_match '^systemctl --user start nice-dns-health\.timer' "$(sed -n "$first,\$p" "$FAKE_LOG")" "$ep: the rollback restarts the controller"
      else
        hold="$(ip_first "$FAKE_LOG" '^launchctl unload .*org\.nice-dns\.health\.plist')"
        first="$(ip_first "$FAKE_LOG" '^container stop ')"
        assert_match '^launchctl load .*org\.nice-dns\.health\.plist' "$(sed -n "$first,\$p" "$FAKE_LOG")" "$ep: the rollback restarts the controller"
      fi
      assert_ne "" "$hold" "$ep: the controller is held:
$(cat -n "$FAKE_LOG")"
      assert_eq 1 "$((hold < first))" "$ep: before the stack stops"
    ) || exit 1
  done
}

t_uninstall_restores_the_recorded_state() {
  local ep
  ip_select
  for ep in $IP_EPS; do
    (
      local before
      dt_world "$ep" "$(dt_fresh_state "$ep")"
      before="$(dt_dns_state)"
      ip_install "$ep"
      assert_rc 0 "$IP_RC" "$ep: install: $IP_OUT"
      ip_install "$ep" uninstall
      assert_rc 0 "$IP_RC" "$ep: uninstall: $IP_OUT"
      assert_eq "$before" "$(dt_dns_state)" "$ep: uninstall restores the recorded state exactly"
      assert_no_path "$(dt_receipt "$(ip_platform "$ep")")" "$ep: and drops the record"
      assert_no_path "$IP_HOME/.local/bin/nice-dns-health" "$ep: the controller is uninstalled"
    ) || exit 1
  done
}

t_external_change_refuses_the_install() {
  local ep
  ip_select
  for ep in $IP_EPS; do
    (
      local before
      dt_world "$ep" "$(dt_fresh_state "$ep")"
      dt_installed "$ep"
      if [ "$(ip_platform "$ep")" = linux ]; then
        rm -f "$FAKE_ROOT/etc/resolv.conf"; printf 'nameserver 10.64.0.1\n' >"$FAKE_ROOT/etc/resolv.conf"
      else
        printf '10.64.0.1\n' >"$FAKE_ROOT/.netsvc/dns/Wi-Fi"
      fi
      before="$(dt_dns_state)"
      ip_install "$ep"
      assert_nonzero "$IP_RC" "$ep: the reinstall refuses: $IP_OUT"
      assert_match 'another owner' "$IP_OUT" "$ep: and says why"
      ip_assert_untouched "$ep"
      assert_eq "$before" "$(dt_dns_state)" "$ep: DNS unchanged"
    ) || exit 1
  done
}

# Public DNS is never written by an installer: only the helpers write the
# host resolver, and they write the pin or the recorded state.
t_no_installer_writes_the_resolver_directly() {
  local f hits
  hits="$(grep -nE 'resolv\.conf|nameserver [0-9]|setdnsservers' \
    "$NICE_DNS_ROOT"/install-deb.sh "$NICE_DNS_ROOT"/install-deb-hardened.sh \
    "$NICE_DNS_ROOT"/install-mac.sh "$NICE_DNS_ROOT"/install-mac-hardened.sh \
    "$NICE_DNS_ROOT"/lib/install.sh "$NICE_DNS_ROOT"/deb/persistent-podman.sh "$NICE_DNS_ROOT"/mac/persist.sh \
    | grep -vE '^[^:]+:[0-9]+:[[:space:]]*#' || true)"
  assert_eq "" "$hits" "no installer code writes resolv.conf or network-service DNS itself"
  for f in 9.9.9.9 1.1.1.1 1.0.0.1; do
    assert_eq "" "$(grep -nF "$f" "$NICE_DNS_ROOT"/deb/custom-dns-deb "$NICE_DNS_ROOT"/mac/start-container-root.sh || true)" "the helpers name no public resolver ($f)"
  done
}

# The installer verbs run under the operator's own sudo; the LaunchAgent's
# passwordless rule stays bounded to the three it needs.
t_agent_sudo_rule_excludes_installer_verbs() {
  local rule
  rule="$(grep -v '^#' "$NICE_DNS_ROOT/mac/start-container.sudoers" | grep -v '^[[:space:]]*$')"
  assert_eq '__USERNAME__ ALL=(root) NOPASSWD: /usr/local/sbin/start-container-root.sh pre, /usr/local/sbin/start-container-root.sh repair-dnsnet, /usr/local/sbin/start-container-root.sh post' "$rule" "the NOPASSWD rule names exactly pre, repair-dnsnet and post"
}

# persist.sh (the real one) loads the start-container agent, whose first run
# pins DNS, only after the controller installed and its installed copy passed
# its self-check.
t_persist_gates_the_agent_on_the_controller() {
  local f="$NICE_DNS_ROOT/mac/persist.sh" inst chk load
  inst="$(grep -n 'nice-dns-health" install' "$f" | head -n 1 | cut -d: -f1)"
  chk="$(grep -n 'self-check' "$f" | grep -v '^[0-9]*:[[:space:]]*#' | head -n 1 | cut -d: -f1)"
  # shellcheck disable=SC2016  # literal $ in patterns
  load="$(grep -n '^launchctl load "\$AGENT_DST"' "$f" | cut -d: -f1)"
  assert_ne "" "$inst" "persist.sh installs the controller"
  assert_ne "" "$chk" "persist.sh runs the installed controller's self-check"
  assert_ne "" "$load" "persist.sh loads the start-container agent"
  assert_eq 1 "$((inst < chk && chk < load))" "install (line $inst), then self-check (line $chk), then the agent load (line $load)"
  assert_match 'exit 1' "$(sed -n "${chk},$((chk + 3))p" "$f")" "a failed self-check exits before the agent load"
}

# A rolled-back deployment that does not answer is reported as such, and DNS
# stays pinned to it (fail closed), never public.
t_rollback_reports_a_previous_stack_that_does_not_answer() {
  local ep
  ip_select
  for ep in $IP_EPS; do
    (
      local dns0
      dt_world "$ep" "$(dt_fresh_state "$ep")"
      dt_installed "$ep"
      dns0="$(dt_dns_state)"
      : >"$FAKE/persist_fail"; : >"$FAKE/rollback_never_ready"
      ip_install "$ep"
      assert_nonzero "$IP_RC" "$ep: $IP_OUT"
      assert_match 'does not answer' "$IP_OUT" "$ep: the rollback says the previous stack does not answer"
      assert_not_match 'which answers again' "$IP_OUT" "$ep: and does not claim it came back"
      assert_eq "$dns0" "$(dt_dns_state)" "$ep: host DNS stays pinned to it"
      assert_match 'rolled-back-not-answering' "$(cat "$IP_STATE"/generations/*-bbbbbbbbbbbb/prepare.tsv)" "$ep: the manifest records it"
    ) || exit 1
  done
}

# A network service that appeared after the install carries DHCP servers,
# not another owner's change; a partly pinned install from before records
# gives each service back what it had.
t_helper_mac_new_and_partly_pinned_services() {
  (
    dt_world install-mac fresh
    dt_helper macos snapshot; dt_helper macos post
    printf 'USB LAN\n' >>"$FAKE_ROOT/.netsvc/list"; printf '10.1.1.1\n' >"$FAKE_ROOT/.netsvc/dns/USB LAN"
    dt_helper macos check
    assert_rc 0 "$DT_RC" "a new service is not a refusal: $DT_OUT"
    dt_helper macos restore
    assert_eq 10.1.1.1 "$(cat "$FAKE_ROOT/.netsvc/dns/USB LAN")" "the new service keeps its servers"
  ) || exit 1
  (
    dt_world install-mac legacy
    printf '192.168.7.1\n' >"$FAKE_ROOT/.netsvc/dns/Ethernet"   # one service reset by hand
    dt_helper macos snapshot
    assert_eq legacy "$(awk -F '\t' '$1 == "origin" { print $2 }' "$(dt_receipt macos)")" "a partly pinned earlier install is legacy"
    dt_helper macos restore
    assert_eq "$(printf 'service Wi-Fi: \nservice Ethernet: 192.168.7.1\nservice Thunderbolt Bridge: ')" "$(dt_dns_state)" "pinned services go back to Empty, the reset one keeps its servers"
  ) || exit 1
}

# The owned files the Linux helper removes are the ones an install saves for
# its rollback (two lists; they must not drift).
t_owned_file_lists_agree() {
  local f missing=""
  # shellcheck disable=SC2016  # literal $ in patterns
  for f in $(sed -n '/^OWNED_FILES=(/,/^)/p' "$NICE_DNS_ROOT/deb/custom-dns-deb" | grep -o '"\$R/[^"]*"' | tr -d '"' | sed 's/^\$R//'); do
    grep -qF "\$R$f\"" "$NICE_DNS_ROOT/lib/install.sh" || missing="$missing $f"
  done
  assert_eq "" "$missing" "every OWNED_FILES path of deb/custom-dns-deb is saved by _nd_inst_owned_paths"
  # shellcheck disable=SC2016  # literal $ in patterns
  assert_ne "" "$(sed -n '/^OWNED_FILES=(/,/^)/p' "$NICE_DNS_ROOT/deb/custom-dns-deb" | grep -c '\$R/')" "the list is read"
}
