#!/usr/bin/env python3
"""Qualification report (sub-plan 05 Task 2.3; ARCH-08, ARCH-09).

Usage: qualification-report.py <qualification receipt.tsv>

Writes a Markdown report to stdout from a qualification receipt and the
receipts it links, and from nothing else: every number is recomputed from
the sample files the receipts pin by sha256. It refuses (exit 2, no report)
unless `tests/reports/verify.sh check <receipt> --require-matrix all`
passes, so a report never describes evidence that does not verify.

Sections: identity (sources, products, receipt chain); the eight-cell
inventory (what each cell was proven by, on which receipt); before/after on
the soak's representative cells (baseline receipt BL-COLD/BL-WARM samples
against the soak receipt's QU-LATENCY samples: n, p50, p95, timeout rate
with its Wilson 95% interval); proof kinds per mandatory fault
(tests/manifests/faults.tsv: "actual host" only when a verified receipt
holds the scenario as pass; "fixture" for unit/integration cases;
"source" for neither); limits and reuse rows of every receipt.
"""
import math
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MAN = os.environ.get("NICE_DNS_TEST_MANIFESTS", os.path.join(ROOT, "tests", "manifests"))
VERIFY = os.path.join(ROOT, "tests", "reports", "verify.sh")


def refuse(msg):
    sys.stderr.write("qualification-report: %s\n" % msg)
    sys.exit(2)


def rows(path):
    with open(path) as f:
        return [l.rstrip("\n").split("\t") for l in f if l.strip() and not l.startswith("#")]


def receipt(path):
    r = {"path": path, "dir": os.path.dirname(os.path.abspath(path)), "rows": rows(path)}
    r["name"] = next(x[1] for x in r["rows"] if x[0] == "receipt")
    r["run_id"] = next(x[1] for x in r["rows"] if x[0] == "run_id")
    return r


def chain(path, seen=None):
    """The receipt and every receipt it links, depth first, each once."""
    seen = seen if seen is not None else {}
    r = receipt(path)
    if r["name"] in seen:
        return seen
    seen[r["name"]] = r
    for x in r["rows"]:
        if x[0] == "requires":
            chain(x[2], seen)
    return seen


def samples(path):
    """(workload, outcome, elapsed_us) of a nice-dns-sample/1 file."""
    out = []
    with open(path) as f:
        lines = f.read().splitlines()
    if not lines or lines[0] != "# schema\tnice-dns-sample/1":
        refuse("%s is not a sample file" % path)
    head = lines[1].split("\t")
    iw, io, ie = head.index("workload"), head.index("outcome"), head.index("elapsed_us")
    for l in lines[2:]:
        if not l or l.startswith("#"):
            continue
        p = l.split("\t")
        out.append((p[iw], p[io], int(p[ie])))
    return out


def nearest_rank(vals, q):
    if not vals:
        return None
    v = sorted(vals)
    k = max(1, int(math.ceil(q / 100.0 * len(v))))
    return v[k - 1]


def wilson(k, n, z=1.959963984540054):
    if n == 0:
        return (0.0, 1.0)
    p = k / n
    d = 1 + z * z / n
    c = p + z * z / (2 * n)
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return (max(0.0, (c - h) / d), min(1.0, (c + h) / d))


def summary(ss, workload):
    """n, p50/p95 over answered and timed-out samples (a timeout counts as
    its elapsed time, failures retained in the denominator), timeouts."""
    w = [s for s in ss if s[0] == workload]
    t = sum(1 for s in w if s[1] == "timeout")
    el = [s[2] for s in w]
    lo, hi = wilson(t, len(w))
    return {"n": len(w), "p50": nearest_rank(el, 50), "p95": nearest_rank(el, 95), "t": t, "lo": lo, "hi": hi}


def ms(us):
    return "-" if us is None else "%.0f ms" % (us / 1000.0)


def pct(x):
    return "%.2f%%" % (100.0 * x)


def main(argv):
    if len(argv) != 1:
        refuse("usage: qualification-report.py <qualification receipt.tsv>")
    path = argv[0]
    if not os.path.isfile(path):
        refuse("no receipt at %s" % path)
    v = subprocess.run(["bash", VERIFY, "check", path, "--require-matrix", "all"],
                       capture_output=True, text=True)
    if v.returncode != 0:
        refuse("the receipt does not verify (--require-matrix all):\n%s%s" % (v.stdout, v.stderr))
    rs = chain(path)
    q = rs.get("qualification")
    if q is None or q["path"] != path:
        refuse("%s is not a qualification receipt" % path)
    for need in ("baseline", "soak"):
        if need not in rs:
            refuse("the chain has no %s receipt" % need)
    out = []
    w = out.append

    w("# nice-dns qualification report")
    w("")
    w("Generated by `tests/reports/qualification-report.py` from receipt `%s` (run `%s`), which "
      "verifies with `--require-matrix all`. Every number below is recomputed from sample files the "
      "receipts pin by sha256." % (q["path"], q["run_id"]))
    w("")
    w("## Identity")
    w("")
    w("| Repository | Commit | State |")
    w("|---|---|---|")
    for x in q["rows"]:
        if x[0] == "source":
            w("| %s | `%s` | %s |" % (x[1], x[2], x[3]))
    w("")
    w("| Receipt | Run | File |")
    w("|---|---|---|")
    for name in ("baseline", "transport", "controller", "installers", "soak", "qualification"):
        if name in rs:
            w("| %s | `%s` | `%s` |" % (name, rs[name]["run_id"], rs[name]["path"]))
    w("")

    w("## Eight-cell inventory")
    w("")
    w("Proof kind: **actual host** (a live scenario that passed on the target, in a verified receipt).")
    w("")
    w("| Cell | Target | Qualification checks | Soak and latency | Baseline |")
    w("|---|---|---|---|---|")
    soakcells = {"%s/%s/%s" % (x[1], x[2], x[3]): x for x in rs["soak"]["rows"] if x[0] == "cell"}
    basecells = {"%s/%s/%s" % (x[1], x[2], x[3]): x for x in rs["baseline"]["rows"] if x[0] == "cell"}
    for x in [y for y in q["rows"] if y[0] == "cell"]:
        key = "%s/%s/%s" % (x[1], x[2], x[3])
        sc = sorted(s[1] for s in q["rows"] if s[0] == "scenario" and s[2] == key and s[3] == "pass")
        soak = ("QU-SOAK, QU-LATENCY on `%s`" % rs["soak"]["run_id"]) if key in soakcells else \
            "by its platform's representative cell (limit latency-per-platform)"
        base = basecells.get(key, [None] * 8)[6] if key in basecells else "-"
        w("| %s | %s | %s | %s | %s |" % (key, x[4], ", ".join(sc) or "-", soak, base))
    w("")

    w("## Before and after (representative cells)")
    w("")
    w("Before: baseline receipt `%s` (BL-COLD, BL-WARM). After: soak receipt `%s` (QU-LATENCY, the "
      "24 h soak's steady samples). Timeouts stay in every denominator; p50/p95 are nearest-rank over "
      "every sample, a timeout counted at its elapsed time. The workloads share a cache class, not a "
      "session: before and after were measured on different days." % (rs["baseline"]["run_id"], rs["soak"]["run_id"]))
    w("")
    w("| Cell | Workload | Before n | Before p50 | Before p95 | Before timeouts (95% CI) | After n | After p50 | After p95 | After timeouts (95% CI) |")
    w("|---|---|---|---|---|---|---|---|---|---|")
    for key in sorted(soakcells):
        base = rs["baseline"]
        art = {(s[1], s[2]): s[4] for s in base["rows"] if s[0] == "scenario"}
        after = [s for s in rs["soak"]["rows"] if s[0] == "scenario" and s[1] == "QU-LATENCY" and s[2] == key]
        if not after:
            refuse("soak receipt has no QU-LATENCY for %s" % key)
        a = samples(os.path.join(rs["soak"]["dir"], after[0][4]))
        for wl, sid in (("cold", "BL-COLD"), ("warm", "BL-WARM")):
            bpath = art.get((sid, key))
            if bpath is None:
                refuse("baseline receipt has no %s for %s" % (sid, key))
            b = summary(samples(os.path.join(base["dir"], bpath)), wl)
            c = summary(a, wl)
            w("| %s | %s | %d | %s | %s | %d/%d (%s-%s) | %d | %s | %s | %d/%d (%s-%s) |" % (
                key, wl, b["n"], ms(b["p50"]), ms(b["p95"]), b["t"], b["n"], pct(b["lo"]), pct(b["hi"]),
                c["n"], ms(c["p50"]), ms(c["p95"]), c["t"], c["n"], pct(c["lo"]), pct(c["hi"])))
    w("")

    w("## Proof kinds per mandatory fault")
    w("")
    w("| Fault | Needs | Fixture proofs | Actual-host proof |")
    w("|---|---|---|---|")
    scen = [x for x in rows(os.path.join(MAN, "scenarios.tsv")) if len(x) >= 6]
    for f in rows(os.path.join(MAN, "faults.tsv")):
        fid, needs, rc = f[0], f[1], f[2]
        fx = sorted("%s/%s %s" % (s[2], s[3], s[4]) for s in scen
                    if s[1] == "fault:" + fid and s[2] in ("unit", "integration"))
        host = "-"
        if rc != "-":
            rn, sid = rc.split(":", 1)
            if rn in rs:
                passed = [s for s in rs[rn]["rows"] if s[0] == "scenario" and s[1] == sid and s[3] == "pass"]
                host = "%s:%s, %d cell(s), receipt `%s`" % (rn, sid, len(passed), rs[rn]["run_id"]) if passed else \
                    "**missing** (%s:%s not pass)" % (rn, sid)
            else:
                host = "**missing** (no %s receipt in the chain)" % rn
        w("| %s | %s | %s | %s |" % (fid, needs, "; ".join(fx) or "-", host))
    w("")

    w("## Limits and reuse")
    w("")
    any_row = False
    for name, r in rs.items():
        for x in r["rows"]:
            if x[0] == "limit":
                w("- **%s** limit `%s` (%s, %s): %s" % (name, x[1], x[2], x[3], x[4]))
                any_row = True
            elif x[0] == "reuse":
                w("- **%s** reuses cell %s from run `%s` at nice-dns `%s` (DEC-009)" % (name, x[1], x[2], x[3]))
                any_row = True
    if not any_row:
        w("- none")
    w("")
    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
