#!/usr/bin/env bash
#
# Fetch two obfs4 bridges from the Tor Project's Moat API on first run, write
# them to ~/.config/nice-dns/bridges.env. The tor-haproxy and tor-socat
# containers consume that file via EnvironmentFile= (Linux quadlets) or
# `set -a; . bridges.env` (install-mac.sh).
#
# Idempotent: if the file already exists and contains BRIDGE1 + BRIDGE2, the
# script exits 0 without touching anything. Re-fetch by `rm`-ing the file.
#
# The Moat "circumvention/builtin" endpoint returns the same default bridges
# Tor Browser ships with — public, rotated by the Tor Project, no CAPTCHA, no
# enumeration concern (they were already public the moment Tor Browser
# shipped them).

set -euo pipefail

CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
BRIDGES_DIR="$CONFIG_HOME/nice-dns"
BRIDGES_FILE="$BRIDGES_DIR/bridges.env"
MOAT_URL="https://bridges.torproject.org/moat/circumvention/builtin"

# Skip work if the file is already populated.
if [[ -f "$BRIDGES_FILE" ]] \
   && grep -q '^BRIDGE1=' "$BRIDGES_FILE" \
   && grep -q '^BRIDGE2=' "$BRIDGES_FILE"; then
    echo "▸ Bridges already configured at $BRIDGES_FILE"
    exit 0
fi

mkdir -p "$BRIDGES_DIR"
chmod 700 "$BRIDGES_DIR"

echo "▸ Fetching default obfs4 bridges from Tor Moat..."

# Fetch the JSON payload. -fsS = fail on HTTP error, silent except on error.
moat_payload="$(curl -fsS --max-time 30 \
    -X POST "$MOAT_URL" \
    -H 'Content-Type: application/vnd.api+json' \
    --data '{"data":[{"version":"0.1.0","type":"moat-circumvention"}]}' \
    || true)"

if [[ -z "$moat_payload" ]]; then
    echo "ERROR: Could not reach $MOAT_URL." >&2
    echo "       Check internet access, or pre-populate $BRIDGES_FILE manually" >&2
    echo "       with two BRIDGE1=/BRIDGE2= obfs4 lines and re-run install." >&2
    exit 1
fi

# Extract obfs4 lines from the JSON. The payload shape is
#   {"obfs4":["obfs4 IP:PORT FPR cert=... iat-mode=N", ...], "snowflake":[...]}
# We use grep -oE with a regex anchored on the literal "obfs4 " prefix so
# we don't depend on jq being installed.
mapfile -t obfs4_lines < <(printf '%s' "$moat_payload" \
    | grep -oE '"obfs4 [^"]+"' \
    | sed 's/^"//; s/"$//')

if (( ${#obfs4_lines[@]} < 2 )); then
    echo "ERROR: Moat returned fewer than 2 obfs4 bridges." >&2
    echo "       Payload: $moat_payload" >&2
    exit 1
fi

# Pick two distinct bridges. Use the first two — they're already shuffled
# server-side. If they happen to share a fingerprint, slide to the next.
bridge1="${obfs4_lines[0]}"
bridge2=""
for line in "${obfs4_lines[@]:1}"; do
    fpr1="$(awk '{print $3}' <<<"$bridge1")"
    fpr2="$(awk '{print $3}' <<<"$line")"
    if [[ "$fpr1" != "$fpr2" ]]; then
        bridge2="$line"
        break
    fi
done

if [[ -z "$bridge2" ]]; then
    echo "ERROR: Moat returned only one unique obfs4 bridge." >&2
    exit 1
fi

# Write atomically. NO surrounding quotes on values: podman --env-file does
# NOT strip quotes (they become part of the value, breaking the obfs4 regex
# in the container's start.sh). systemd EnvironmentFile= and bash `source`
# both parse "KEY=value with spaces" correctly without quoting, so unquoted
# is the only format that works for all three consumers.
umask 077
tmp="$(mktemp "$BRIDGES_FILE.XXXXXX")"
{
    printf '# Auto-generated by nice-dns/scripts/fetch-bridges.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# Source: %s (Tor Project built-in obfs4 list)\n' "$MOAT_URL"
    printf "# Re-fetch with: rm '%s' && nice-dns-install rerun\n" "$BRIDGES_FILE"
    printf '# Format: KEY=VALUE  (NO surrounding quotes — podman --env-file does not strip them)\n'
    printf 'BRIDGE1=%s\n' "$bridge1"
    printf 'BRIDGE2=%s\n' "$bridge2"
} > "$tmp"
mv "$tmp" "$BRIDGES_FILE"
chmod 600 "$BRIDGES_FILE"

echo "✓ Wrote $BRIDGES_FILE (mode 600)"
echo "  BRIDGE1 fingerprint: $(awk '{print $3}' <<<"$bridge1")"
echo "  BRIDGE2 fingerprint: $(awk '{print $3}' <<<"$bridge2")"
